// Code generated by Cored SDK Generator. DO NOT EDIT.
package coim

import (
	"context"

	cocore "github.com/cored-im/openapi-sdk-go/core"
)

// Set typing status (Request)
type CreateTypingReq struct {
	ChatId *string `json:"chat_id,omitempty"` // Chat ID
}

// Set typing status (Response)
type CreateTypingResp struct {
}

// Set typing status
//
// Set the typing status, lasts only 5 seconds, direct messages only
func (impl *v1Chat) CreateTyping(ctx context.Context, req *CreateTypingReq) (*CreateTypingResp, error) {
	apiResp, err := impl.config.ApiClient.Request(ctx, &cocore.ApiRequest{
		Method: "POST",
		Path:   "/oapi/im/v1/chats/:chat_id/typing",
		Body:   req,
		PathParams: map[string]string{
			"chat_id": stringOrEmpty(req.ChatId),
		},
		WithAppAccessToken: true,
	})
	if err != nil {
		return nil, err
	}
	var resp CreateTypingResp
	if err = apiResp.JSON(&resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Clear typing status (Request)
type DeleteTypingReq struct {
	ChatId *string `json:"chat_id,omitempty"` // Chat ID
}

// Clear typing status (Response)
type DeleteTypingResp struct {
}

// Clear typing status
//
// Direct messages only
func (impl *v1Chat) DeleteTyping(ctx context.Context, req *DeleteTypingReq) (*DeleteTypingResp, error) {
	apiResp, err := impl.config.ApiClient.Request(ctx, &cocore.ApiRequest{
		Method: "DELETE",
		Path:   "/oapi/im/v1/chats/:chat_id/typing",
		Body:   req,
		PathParams: map[string]string{
			"chat_id": stringOrEmpty(req.ChatId),
		},
		WithAppAccessToken: true,
	})
	if err != nil {
		return nil, err
	}
	var resp DeleteTypingResp
	if err = apiResp.JSON(&resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
