// Code generated by Cored SDK Generator. DO NOT EDIT.
package coim

// Message type
const (
	MessageType_TEXT               string = "text"               // Text
	MessageType_IMAGE              string = "image"              // Image
	MessageType_STICKER            string = "sticker"            // Sticker
	MessageType_VIDEO              string = "video"              // Video
	MessageType_AUDIO              string = "audio"              // Audio
	MessageType_FILE               string = "file"               // File
	MessageType_USER_CARD          string = "user_card"          // User card
	MessageType_GROUP_CARD         string = "group_card"         // Group card
	MessageType_GROUP_ANNOUNCEMENT string = "group_announcement" // Group announcement
	MessageType_CARD               string = "card"               // Card
)

// Attachment type
const (
	MessageTextAttachmentType_IMAGE string = "image" // Image
)

// Message status
const (
	MessageStatus_VISIBLE  string = "visible"  // Visible
	MessageStatus_RECALLED string = "recalled" // Recalled
)
