// Code generated by Cored SDK Generator. DO NOT EDIT.
package coim

import (
	"sync"

	cocore "github.com/cored-im/openapi-sdk-go/core"
)

type v1Message struct {
	config *cocore.Config
	Event  *v1MessageEvent
}

type v1MessageEvent struct {
	config     *cocore.Config
	handlerMap sync.Map
}
