// Code generated by Cored SDK Generator. DO NOT EDIT.
package coim

// Message content
type MessageContent struct {
	Text              *MessageText              `json:"text,omitempty"`               // Text message
	Image             *MessageImage             `json:"image,omitempty"`              // Image message
	Sticker           *MessageSticker           `json:"sticker,omitempty"`            // Sticker message
	Video             *MessageVideo             `json:"video,omitempty"`              // Video message
	Audio             *MessageAudio             `json:"audio,omitempty"`              // Audio message
	File              *MessageFile              `json:"file,omitempty"`               // File message
	UserCard          *MessageUserCard          `json:"user_card,omitempty"`          // User card message
	GroupCard         *MessageGroupCard         `json:"group_card,omitempty"`         // Group card message
	GroupAnnouncement *MessageGroupAnnouncement `json:"group_announcement,omitempty"` // Group announcement
	Card              *MessageCard              `json:"card,omitempty"`               // Card message
}

// Text message
type MessageText struct {
	Content         *string                   `json:"content,omitempty"`           // Content
	AttachmentList  []*MessageTextAttachment  `json:"attachment_list,omitempty"`   // Attachment list, referenced in content as {{attach:id}}
	MentionUserList []*MessageTextMentionUser `json:"mention_user_list,omitempty"` // Mentioned user list, referenced in content as {{mention:user_id}}. Use user_id "all" to mention everyone
	EmojiList       []*MessageTextEmoji       `json:"emoji_list,omitempty"`        // Emoji list, referenced in content as {{emoji:emoji_id}}
}

// Attachment
type MessageTextAttachment struct {
	AttachmentId      *string                       `json:"attachment_id,omitempty"`      // Attachment ID, referenced in content as {{id}}, defined by the client
	AttachmentType    *string                       `json:"attachment_type,omitempty"`    // Attachment type
	AttachmentContent *MessageTextAttachmentContent `json:"attachment_content,omitempty"` // Attachment content
}

// Attachment content
type MessageTextAttachmentContent struct {
	Image *FileImage `json:"image,omitempty"` // Image
}

// Image file
type FileImage struct {
	Image              *File   `json:"image,omitempty"`                // Image, max width/height 1024
	ImageWidth         *uint64 `json:"image_width,omitempty"`          // Image width
	ImageHeight        *uint64 `json:"image_height,omitempty"`         // Image height
	ImageOrigin        *File   `json:"image_origin,omitempty"`         // Original image
	ImageOriginWidth   *uint64 `json:"image_origin_width,omitempty"`   // Original image width
	ImageOriginHeight  *uint64 `json:"image_origin_height,omitempty"`  // Original image height
	ImageThumbBytes    []byte  `json:"image_thumb_bytes,omitempty"`    // Thumbnail data, max width/height 40
	ImageThumbMime     *string `json:"image_thumb_mime,omitempty"`     // Thumbnail MIME type
	ImageDominantColor *string `json:"image_dominant_color,omitempty"` // Dominant color of the image, in #ffffff format
}

// File
type File struct {
	FileId         *string     `json:"file_id,omitempty"`         // File ID
	FileMime       *string     `json:"file_mime,omitempty"`       // File MIME type
	FileSize       *uint64     `json:"file_size,omitempty"`       // File size
	FileEncryption *Encryption `json:"file_encryption,omitempty"` // File encryption
}

// Encryption
type Encryption struct {
	EncryptionAlgorithm *string `json:"encryption_algorithm,omitempty"` // Encryption algorithm
	EncryptionKey       []byte  `json:"encryption_key,omitempty"`       // Encryption key
	EncryptedSize       *uint64 `json:"encrypted_size,omitempty"`       // Encrypted size
}

// Mentioned user
type MessageTextMentionUser struct {
	UserId   *UserId `json:"user_id,omitempty"`    // User ID
	UserName *string `json:"user_name,omitempty"`  // Username at the time of mention
	IsInChat *bool   `json:"is_in_chat,omitempty"` // Whether the user was in the chat at the time
}

// User ID
type UserId struct {
	UserId      *string `json:"user_id,omitempty"`       // User ID in the platform. The same user has the same user_id across all apps
	UnionUserId *string `json:"union_user_id,omitempty"` // User ID within the same app group. The same user has the same union_user_id across different apps in the same group
	OpenUserId  *string `json:"open_user_id,omitempty"`  // User ID within an app. The same user has different open_user_id values in different apps
}

type MessageTextEmoji struct {
	EmojiId   *string `json:"emoji_id,omitempty"`   // Emoji ID
	EmojiName *string `json:"emoji_name,omitempty"` // Emoji name at the time
}

// Image message
type MessageImage struct {
	Image *FileImage `json:"image,omitempty"` // Image
}

// Sticker message
type MessageSticker struct {
	Sticker *Sticker `json:"sticker,omitempty"` // Sticker
}

// Sticker
type Sticker struct {
	StickerId       *string           `json:"sticker_id,omitempty"`        // Sticker ID
	StickerName     *string           `json:"sticker_name,omitempty"`      // Sticker name
	StickerNameI18n map[string]string `json:"sticker_name_i18n,omitempty"` // Sticker internationalized name
	StickerImage    *FileImage        `json:"sticker_image,omitempty"`     // Sticker image
}

// Video message
type MessageVideo struct {
	Video *FileVideo `json:"video,omitempty"` // Video
}

// Video file
type FileVideo struct {
	Video         *File      `json:"video,omitempty"`          // Video
	VideoWidth    *uint64    `json:"video_width,omitempty"`    // Video width
	VideoHeight   *uint64    `json:"video_height,omitempty"`   // Video height
	VideoDuration *float64   `json:"video_duration,omitempty"` // Video duration
	VideoPreview  *FileImage `json:"video_preview,omitempty"`  // Video preview image
}

// Audio message
type MessageAudio struct {
	Audio *FileAudio `json:"audio,omitempty"` // Audio
}

// Audio file
type FileAudio struct {
	Audio         *File    `json:"audio,omitempty"`          // Audio
	AudioDuration *float64 `json:"audio_duration,omitempty"` // Audio duration
}

// File message
type MessageFile struct {
	File     *File   `json:"file,omitempty"`     // File
	Filename *string `json:"filename,omitempty"` // Filename
}

// User card message
type MessageUserCard struct {
	UserId *UserId `json:"user_id,omitempty"` // User ID
}

// Group card message
type MessageGroupCard struct {
	ChatId *string `json:"chat_id,omitempty"` // Chat ID
}

// Group announcement
type MessageGroupAnnouncement struct {
	MessageText *MessageText `json:"message_text,omitempty"` // Announcement content
}

// Card message
type MessageCard struct {
	Schema *string        `json:"schema,omitempty"` // Card schema version
	V1     *MessageCardV1 `json:"v1,omitempty"`     // V1
}

// V1
type MessageCardV1 struct {
	Header *MessageCardV1Header `json:"header,omitempty"` // Card header
	Body   *MessageCardV1Body   `json:"body,omitempty"`   // Card body
	Footer *MessageCardV1Footer `json:"footer,omitempty"` // Card footer
}

// Card header
type MessageCardV1Header struct {
	Title     *string           `json:"title,omitempty"`      // Title text
	TitleI18n map[string]string `json:"title_i18n,omitempty"` // Internationalized title text
	Template  *string           `json:"template,omitempty"`   // Title color template
}

// Card body
type MessageCardV1Body struct {
	MessageText     *MessageText            `json:"message_text,omitempty"`      // Card body text message
	MessageTextI18n map[string]*MessageText `json:"message_text_i18n,omitempty"` // Internationalized card body text message
}

// Card footer
type MessageCardV1Footer struct {
	ButtonList  []*MessageCardV1Button `json:"button_list,omitempty"`  // Button list
	ButtonAlign *string                `json:"button_align,omitempty"` // Button alignment
}

// Card button
type MessageCardV1Button struct {
	ButtonText     *string                  `json:"button_text,omitempty"`      // Button text
	ButtonTextI18n map[string]string        `json:"button_text_i18n,omitempty"` // Internationalized button text
	Template       *string                  `json:"template,omitempty"`         // Button style template, values: default, primary, danger, primary_text, danger_text, primary_filled, danger_filled
	Link           *MessageCardV1ButtonLink `json:"link,omitempty"`             // Button link
}

// Link
type MessageCardV1ButtonLink struct {
	Url        *string `json:"url,omitempty"`         // Default URL
	AndroidUrl *string `json:"android_url,omitempty"` // Android URL
	IosUrl     *string `json:"ios_url,omitempty"`     // iOS URL
	PcUrl      *string `json:"pc_url,omitempty"`      // Desktop URL
}

// Message
type Message struct {
	MessageId        *string           `json:"message_id,omitempty"`         // Message ID
	MessageType      *string           `json:"message_type,omitempty"`       // Message type
	MessageStatus    *string           `json:"message_status,omitempty"`     // Message status
	MessageContent   *MessageContent   `json:"message_content,omitempty"`    // Message content
	MessageCreatedAt *uint64           `json:"message_created_at,omitempty"` // Message creation time (milliseconds)
	ChatId           *string           `json:"chat_id,omitempty"`            // Chat ID
	ChatSeqId        *uint64           `json:"chat_seq_id,omitempty"`        // Server-generated monotonically increasing ID at the chat level, used for ordering within a chat
	SenderId         *UserId           `json:"sender_id,omitempty"`          // Sender ID
	Reply            *MessagePropReply `json:"reply,omitempty"`              // Reply properties
}

// Message reply properties
type MessagePropReply struct {
	ReplyMessageId *string `json:"reply_message_id,omitempty"` // ID of the message being replied to
}
