// Code generated by Cored SDK Generator. DO NOT EDIT.
package coserviceim

import (
	cocore "github.com/cored-im/openapi-sdk-go/core"
	v1 "github.com/cored-im/openapi-sdk-go/service/im/v1"
)

type Service struct {
	*v1.V1
}

func New(config *cocore.Config) *Service {
	return &Service{
		V1: v1.New(config),
	}
}
